exec-once = waybar
exec-once = swayosd-server
exec-once = swww-daemon
exec-once = sh -c 'sleep 0.3 && swww img /home/bob/Pictures/373472321_264028466567597_4894552466123986584_n.png --resize fit --fill-color 000000'
