# General setup

exec-once = waybar          # widget bar
exec-once = swayosd-server  # for volume and brightness indicators
exec-once = swww-daemon     # wallpaper service
                            # sets wallpaper
exec-once = sh -c 'sleep 0.3 && swww img /home/bob/Pictures/wallpaper_iguana-bust.png --resize fit --fill-color 000000'
                            # add Desktop integration layer
exec-once = xdg-desktop-portal-hyprland


# Startup apps

exec-once = thunderbird     # start thunderbird
                            # start agenda
exec-once = /home/bob/Notebooks/emacs-notebook.sh

