input {
#    kb_layout = wym
#    kb_variant = basic
    kb_file = ~/.config/hypr/wym.xkb
#    kb_model =
#    kb_options =
#    kb_rules =
    follow_mouse = 0
    sensitivity = 0 # -1.0 - 1.0, 0 means no modification.
    touchpad {
        tap-to-click = true        # keep tap-to-click if you want
        clickfinger_behavior = true# left=1 finger, right=2 finger, middle=3 finger
        tap-and-drag = false       # this disables the annoying behavior
        drag_lock = false          # optional, also related
        natural_scroll = false
    }
}


# See https://wiki.hypr.land/Configuring/Gestures
gesture = 3, horizontal, workspace
# Example per-device config
# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more


device {
    name = epic-mouse-v1
    sensitivity = -0.5
}
