### window-rules.conf ###

windowrule {
# Open all windows (except Thunderbirf)
# on the current workspace
    name = open-on-current-workspace
    match:class = negative:^(org\.mozilla\.Thunderbird$)
    workspace = current
}


windowrule {
# Open my org agenda on workspace 2
    name = emacs-agenda
    match:class = ^(Emacs)$
    match:title = ^(agenda)$
    workspace = 1 silent
}


windowrule {
# Open thunderbird on Workspace 1
    name = thunderbird-placement
    match:class = org.mozilla.Thunderbird
    workspace = 2 silent
}


windowrule {
# Hyprland default
# Ignore maximize requests from all apps.
# You'll probably like this.
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
# Hyprland default
# Fix some dragging issues with XWayland
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}


windowrule {
# Hyprland default
# Hyprland-run windowrule
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

