# monitors
monitor = eDP-1,2560x1600@60,0x0,1
monitor = desc:Hewlett Packard HP ZR2440w CN42200288,1920x1200@60,2560x-1080,1,transform,1
monitor = desc:BNQ BenQ GL2440H J3B14602SL0,1920x1080@60,640x-1080,1

# explicit default workspace per monitor
workspace = 1, monitor:eDP-1, default:true, persistent:true
workspace = 7, monitor:desc:Hewlett Packard HP ZR2440w CN42200288, default:true, persistent:true
workspace = 13, monitor:desc:BNQ BenQ GL2440H J3B14602SL0, default:true, persistent:true

# bind the remaining workspaces to the intended monitor
workspace = 2-6, monitor:eDP-1, persistent:true
workspace = 8-12, monitor:desc:Hewlett Packard HP ZR2440w CN42200288, persistent:true
workspace = 14-18, monitor:desc:BNQ BenQ GL2440H J3B14602SL0, persistent:true
