background {
    monitor =
    path = /home/bob/Pictures/tromp_cunucu.jpg 
    blur_passes = 4
    blur_size = 1
    noise = 0.2
    contrast = 0.8
    brightness = 0.4
    vibrancy = 1
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(255, 255, 255, 0.2)
    inner_color = rgba(0, 0, 0, 0.5)
    font_color = rgba(255, 255, 255, 1.0)
    fade_on_empty = false
    rounding = 10
    position = -850, -500
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%H:%M')"
    font_size = 64
    color = rgba(255,255,255,1.0)
    position = -850, -400
    halign = center
    valign = center
}
